# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          /blog/:categories/:year/:month/:day/:title.html

# Setup
title:               Pit Stop
tagline:             'Enjoy Life, Enjoy Everyday.'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lbay.me
baseurl:             ''
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              ayouwei
  url:               https://twitter.com/ayouwei
  email:             ji@lbay.me

# Custom vars
version:             0.0.1
